=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/template.dtd
<!-- ==========================================================================
 This is the DTD for phpLDAPAdmin Templates (draft).

 Copyright (c) 2005 <adezorzi AT rhx DOT it>

 temporary URI for the DTD: http://www.phamm.org/DTD/pla-template-strict.dtd
 Validate your templates here: http://www.stg.brown.edu/service/xmlvalid/
========================================================================== -->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (title,regexp?,icon?,description?,askcontainer?,rdn?,
			destinationcontainer?,action?,leaf?,
			visible?,invalid?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (array?, value*, cols?, description?, display?, helper?, hidden?, readonly?, hint?,
			icon?, onchange*, order?, override?, page?, post?,minvalnb?,maxvalnb?,
			presubmit?, rows?, spacer*, type?, option*, verify?)>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (value*,display?,hint?,id?,location?,option*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT visible (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>
<!ELEMENT destinationcontainer (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT leaf (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT array (#PCDATA)>
<!ELEMENT minvalnb (#PCDATA)>
<!ELEMENT maxvalnb (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT readonly (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT option (#PCDATA)>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/courierMailAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Courier Mail Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail_account.png</icon>
<description>New Courier Mail Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>
<invalid>0</invalid>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="courierMailAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>Given Name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<icon>images/uid.png</icon>
	<!--<onchange>autoFill:homeDirectory,/home/users/%uid%</onchange>-->
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<icon>images/terminal.png</icon>
	<value>=php.GetNextNumber(/,uid)</value>
	<readonly>1</readonly>
	<order>6</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<option>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</option>
	<order>7</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="homeDirectory">
	<display>Home Directory</display>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="mail">
        <display>Email</display>
	<icon>images/mail.png</icon>
        <order>9</order>
        <page>1</page>
</attribute>
<attribute id="mailbox">
	<display>Mailbox</display>
	<order>10</order>
	<page>1</page>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>images/lock.png</icon>
	<type>password</type>
	<verify>1</verify>
	<helper>
		<display>Encryption</display>
		<id>enc</id>
		<option>blowfish</option>
		<option>clear</option>
		<option>crypt</option>
		<option>ext_des</option>
		<option>md5</option>
		<option>md5crypt</option>
		<option>sha</option>
		<option>smd5</option>
		<option>ssha</option>
		<value>md5</value>
	</helper>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<order>11</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/posixGroup.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Posix Group</title>
<!-- <regexp>^ou=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>New Posix Group</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<hint>Automatically determined</hint>
	<order>2</order>
	<page>1</page>
	<value>=php.GetNextNumber(/,gid)</value>
	<readonly>1</readonly>
	<spacer>1</spacer>
	<!-- <option>=php.GetNextNumber(/,gid,false,(&amp;(objectClass=posixGroup)),*2;+1000)</option> -->
</attribute>
<attribute id="memberUid">
	<display>Users</display>
	<!-- <option>=php.MultiList(/,(objectClass=posixAccount),uid,%cn% (%uid|-4%))</option> -->
	<hidden>0</hidden>
	<order>3</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/sambaGroupMapping.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Group Mapping</title>
<!-- <regexp>^ou=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>New Samba3 Group Mapping</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
<objectClass id="sambaGroupMapping"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="displayName">
	<display>Windows Name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<hint>Automatically determined</hint>
	<value>=php.GetNextNumber(/,gid,true,(&amp;(objectClass=sambaDomain)(sambaDomainName=mysambadomain))</value>
	<readonly>1</readonly>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<option>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</option>
	<helper>
		<id>sidsuffix</id>
		<option>=php.GetNextNumber(/,gid,false,(&amp;(objectClass=sambaDomain)(sambaDomainName=mysambadomain)),*2;+1000)</option>
	</helper>
	<post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="sambaGroupType">
	<display>Samba Group Type</display>
	<option id="2">Domain Group</option>
	<option id="4">Local Group</option>
	<option id="5">Well-known Group</option>
	<value>2</value>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="memberUid">
	<display>Users</display>
	<type>multiselect</type>
	<option>=php.MultiList(/,(objectClass=posixAccount),uid,%cn% %uid|-4/U%,memberUid,dmdName=users:::dc=localdomain,root => cn=root; nobody => cn=nobody,cn,,,)</option>
	<value>=php.MultiList(/,(&amp;(objectClass=posixAccount)(gidNumber=29999)),uid)</value>
	<size>10</size>
	<hidden>0</hidden>
	<order>10</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/sambaMachine.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Machine</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/server.png</icon>
<description>New Samba3 Machine</description>
<askcontainer>1</askcontainer>
<rdn>uid</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
<objectClass id="account"></objectClass>
</objectClasses>

<attributes>
<attribute id="uid">
	<display>Machine Name</display>
	<hint>The machine name should end with a $</hint>
        <icon>images/terminal.png</icon>
	<onchange>autoFill:cn,%uid%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
        <display>UID Number</display>
        <hint>Automatically determined</hint>
        <value>=php.GetNextNumber(/,uid)</value>
	<readonly>1</readonly>
        <order>2</order>
        <page>1</page>
</attribute>
<attribute id="gidNumber">
        <display>GID Number</display>
	<option>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</option>
        <order>3</order>
        <page>1</page>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
        <option>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</option>
	<helper>
		<id>sidsuffix</id>
		<value></value>
	</helper>
        <post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sambaAcctFlags">
	<value>[W]</value>
	<hidden>1</hidden>
</attribute>
<attribute id="homeDirectory">
	<value>/dev/null</value>
	<hidden>1</hidden>
</attribute>
<attribute id="cn">
	<value></value>
	<hidden>1</hidden>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/simpleSecurityObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Simple Security Object</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Simple Security Object</description>
<askcontainer>1</askcontainer>
<rdn>userid</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="account"></objectClass>
<objectClass id="simpleSecurityObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="userid">
	<display>User Name</display>
	<icon>images/uid.png</icon>
	<order>1</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>images/lock.png</icon>
	<type>password</type>
	<verify>1</verify>
	<helper>
		<display>Encryption</display>
		<id>enc</id>
		<option>blowfish</option>
		<option>clear</option>
		<option>crypt</option>
		<option>ext_des</option>
		<option>md5</option>
		<option>md5crypt</option>
		<option>sha</option>
		<option>smd5</option>
		<option>ssha</option>
		<value>md5</value>
	</helper>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<order>5</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/SUSE-sambaGroupMapping.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Group Mapping - SUSE</title>
<!-- <regexp>^ou=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>New Samba3 Group Mapping</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
<objectClass id="namedObject"></objectClass>
<objectClass id="sambaGroupMapping"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="displayName">
	<display>Windows Name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<hint>Automatically determined</hint>
	<value>=php.GetNextNumber(/,gid)</value>
	<readonly>1</readonly>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<option>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</option>
	<helper>
		<id>sidsuffix</id>
		<value></value>
	</helper>
	<post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="sambaGroupType">
	<display>Samba Group Type</display>
	<option id="2">Domain Group</option>
	<option id="4">Local Group</option>
	<option id="5">Well-known Group</option>
	<value>2</value>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="memberUid">
	<maxvalnb>10</maxvalnb>
	<display>Users</display>
	<type>Dn</type>
	<hidden>0</hidden>
	<order>10</order>
	<page>1</page>
</attribute>
</attributes>
</template>
