=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/template.dtd
<!-- ==========================================================================
 This is the DTD for phpLDAPAdmin Templates (draft).

 Copyright (c) 2005 <adezorzi AT rhx DOT it>

 temporary URI for the DTD: http://www.phamm.org/DTD/pla-template-strict.dtd
 Validate your templates here: http://www.stg.brown.edu/service/xmlvalid/
========================================================================== -->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (title,regexp?,icon?,description?,askcontainer?,rdn?,
			destinationcontainer?,action?,leaf?,
			visible?,invalid?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (array?, value*, cols?, description?, display?, helper?, hidden?, readonly?, hint?,
			icon?, onchange*, order?, override?, page?, post?,minvalnb?,maxvalnb?,
			presubmit?, rows?, spacer*, type?, option*, verify?)>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (value*,display?,hint?,id?,location?,option*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT visible (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>
<!ELEMENT destinationcontainer (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT leaf (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT array (#PCDATA)>
<!ELEMENT minvalnb (#PCDATA)>
<!ELEMENT maxvalnb (#PCDATA)>
<!ELEMENT cols (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT readonly (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT option (#PCDATA)>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/SUSE-posixGroup.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Posix Group - SUSE</title>
<!-- <regexp>^ou=.*,</regexp> -->
<icon>images/ou.png</icon>
<description>Posix Group - SUSE</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
<objectClass id="namedObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<hint>Automatically determined</hint>
	<value>=php.GetNextNumber(/,gid)</value>
	<readonly>1</readonly>
	<order>2</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="memberUid">
	<maxvalnb>10</maxvalnb>
	<display>Users</display>
	<type>Dn</type>
	<hidden>0</hidden>
	<order>3</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/posixAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>User Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New User Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%givenName|0-1/l%%sn/l%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%givenName|0-1/l%%sn/l%</onchange>
	<!-- <onchange>autoFill:homeDirectory,/home/users/%uid|0-1/l%/%uid%</onchange> -->
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>autoFill:homeDirectory,/home/users/%uid%</onchange>
	<order>4</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<!-- <onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange> -->
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<icon>images/terminal.png</icon>
	<order>6</order>
	<page>1</page>
	<value>=php.GetNextNumber(/,uid)</value>
	<readonly>1</readonly>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<!-- <onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange> -->
	<order>7</order>
	<page>1</page>
	<option>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</option>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<order>9</order>
	<page>1</page>
	<!-- <option>=php.PickList(/,(objectClass=posixAccount),loginShell,%loginShell%)</option> -->
	<option>/bin/sh</option>
	<option>/bin/tsh</option>
	<option>/bin/csh</option>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>images/lock.png</icon>
	<type>password</type>
	<verify>1</verify>
	<helper>
		<display>Encryption</display>
		<id>enc</id>
		<option>blowfish</option>
		<option>clear</option>
		<option>crypt</option>
		<option>ext_des</option>
		<option>md5</option>
		<option>md5crypt</option>
		<option>sha</option>
		<option>smd5</option>
		<option>ssha</option>
		<value>md5</value>
	</helper>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/sambaSamAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Samba3 Account</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Samba3 Account</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<onchange>autoFill:uid,%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<order>4</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<hint>Automatically determined</hint>
	<value>=php.GetNextNumber(/,uid)</value>
	<order>5</order>
	<page>1</page>
	<readonly>1</readonly>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<option>=php.PickList(/,(objectClass=sambaDomain),sambaSID,%sambaSID% (%sambaDomainName%))</option>
	<helper>
		<id>sidsuffix</id>
		<option>=php.GetNextNumber(/,uid,false,,*2;+1000)</option>
	</helper>
	<post>=php.Join(-,(%sambaSID%,%sidsuffix%))</post>
	<order>6</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>images/lock.png</icon>
	<onchange>autoFill:sambaLMPassword,%userPassword%</onchange>
	<onchange>autoFill:sambaNTPassword,%userPassword%</onchange>
	<type>password</type>
	<verify>1</verify>
	<helper>
		<display>Encryption</display>
		<id>enc</id>
		<option>blowfish</option>
		<option>clear</option>
		<option>crypt</option>
		<option>ext_des</option>
		<option>md5</option>
		<option>md5crypt</option>
		<option>sha</option>
		<option>smd5</option>
		<option>ssha</option>
		<value>md5</value>
	</helper>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<order>7</order>
	<page>1</page>
</attribute>
<attribute id="sambaLMPassword">
	<display>LM Password</display>
	<type>password</type>
	<post>=php.SambaPassword(LM,%sambaLMPassword%)</post>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="sambaNTPassword">
	<display>NT Password</display>
	<type>password</type>
	<post>=php.SambaPassword(NT,%sambaNTPassword%)</post>
	<order>9</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<icon>images/terminal.png</icon>
	<!-- <option>=php.PickList(/,(objectClass=posixAccount),loginShell,%loginShell%)</option> -->
	<option>/bin/sh</option>
	<option>/bin/tsh</option>
	<option>/bin/csh</option>
	<order>10</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>autoFill:homeDirectory,/home/users/%gidNumber|0-0/T%/%uid|3-%</onchange>
	<option>=php.PickList(/,(objectClass=posixGroup),gidNumber,%cn%)</option>
	<order>11</order>
	<page>1</page>
</attribute>
<attribute id="sambaPrimaryGroupSID">
	<display>Primary Group ID</display>
	<option>=php.PickList(/,(objectClass=sambaGroupMapping),sambaSID,%sambaSID% (%cn%),sambaPrimaryGroupSID)</option>
	<helper>
		<id>sidpgsuffix</id>
		<value></value>
	</helper>
	<post>=php.Join(-,(%sambaPrimaryGroupSID%,%sidpgsuffix%))</post>
	<order>13</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<order>14</order>
	<page>1</page>
</attribute>
<attribute id="sambaAcctFlags">
	<value>[U]</value>
	<hidden>1</hidden>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/mozillaOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Address Book Entry (mozillaAbPersonAlpha)</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Address Book Entry</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="mozillaAbPersonAlpha"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First Name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%sn% %givenName%</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last Name</display>
	<onchange>autoFill:cn,%sn% %givenName%</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
</attribute>
<attribute id="mozillaNickName">
	<display>Nickname</display>
	<order>4</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>5</order>
</attribute>
<attribute id="mozillaSecondEmail">
	<display>Additional email</display>
	<order>6</order>
	<spacer>1</spacer>
</attribute>
<attribute id="nsAIMid">
	<display>Screen Name</display>
	<order>7</order>
</attribute>
<attribute id="telephoneNumber">
	<display>Work Phone</display>
	<icon>images/phone.png</icon>
	<order>8</order>
</attribute>
<attribute id="homePhone">
	<display>Home Phone</display>
	<order>9</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>10</order>
</attribute>
<attribute id="pager">
	<display>Page</display>
	<order>11</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>12</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mozillaHomeStreet">
	<display>Home Address</display>
	<order>13</order>
</attribute>
<attribute id="mozillaHomeStreet2">
	<display>Home Address 2</display>
	<order>14</order>
</attribute>
<attribute id="mozillaHomeLocalityName">
	<display>Home City</display>
	<order>15</order>
</attribute>
<attribute id="mozillaHomeState">
	<display>Home State</display>
	<order>16</order>
</attribute>
<attribute id="mozillaHomePostalCode">
	<display>Home ZIP/Postal Code</display>
	<order>17</order>
</attribute>
<attribute id="mozillaHomeCountryName">
	<display>Home Country</display>
	<order>18</order>
</attribute>
<attribute id="mozillaHomeUrl">
	<display>Home Web page</display>
	<order>19</order>
	<spacer>1</spacer>
</attribute>
<attribute id="title">
	<display>Work Title</display>
	<order>20</order>
</attribute>
<attribute id="ou">
	<display>Work Department</display>
	<order>21</order>
</attribute>
<attribute id="o">
	<display>Work Organization</display>
	<order>22</order>
</attribute>
<attribute id="street">
	<display>Work Address</display>
	<order>23</order>
</attribute>
<attribute id="mozillaWorkStreet2">
	<display>Work Address 2</display>
	<order>24</order>
</attribute>
<attribute id="l">
	<display>Work City</display>
	<order>25</order>
</attribute>
<attribute id="st">
	<display>Work State/Province</display>
	<order>26</order>
</attribute>
<attribute id="postalCode">
	<display>Work ZIP/Postal Code</display>
	<order>27</order>
</attribute>
<attribute id="c">
	<display>Work Country</display>
	<order>28</order>
</attribute>
<attribute id="mozillaWorkUrl">
	<display>Work Web page</display>
	<order>29</order>
</attribute>
<attribute id="description">
	<display>Note</display>
	<order>30</order>
</attribute>
<attribute id="mozillaCustom1">
	<display>Custom 1</display>
	<order>31</order>
</attribute>
<attribute id="mozillaCustom2">
	<display>Custom 2</display>
	<order>32</order>
</attribute>
<attribute id="mozillaCustom3">
	<display>Custom 3</display>
	<order>33</order>
</attribute>
<attribute id="mozillaCustom4">
	<display>Custom 4</display>
	<order>34</order>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/alias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<!--This template doesnt work needs modification to the Engine.-->
<template>
<title>LDAP Alias</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail_alias.png</icon>
<description>New LDAP Alias</description>
<askcontainer>1</askcontainer>
<rdn>uid</rdn>
<visible>1</visible>
<invalid>0</invalid>

<objectClasses>
<objectClass id="alias"></objectClass>
<objectClass id="extensibleObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="aliasedObjectName">
	<display>Alias To</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<order>2</order>
	<page>1</page>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/modification/inetOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Address Book Entry</title>
<regexp>^uid=.*,</regexp>
<icon>images/user.png</icon>
<visible>0</visible>
<rdn>uid</rdn>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="top"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<readonly>1</readonly>
	<order>3</order>
	<spacer>1</spacer>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>4</order>
</attribute>
<attribute id="street">
	<display>Street</display>
	<icon>images/mail.png</icon>
	<type>textarea</type>
	<cols>50</cols>
	<rows>4</rows>
	<order>5</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<option>Berlin</option>
	<option>London</option>
	<option>Paris</option>
	<option>Washington</option>
	<option>Other</option>
	<order>6</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>7</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<maxlength>5</maxlength>
	<order>8</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>images/phone.png</icon>
	<order>9</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>10</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>11</order>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>12</order>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/kolabPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template>
<title>Kolab User Entry</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/user.png</icon>
<description>New Address Book Entry</description>
<askcontainer>1</askcontainer>
<rdn>cn</rdn>
<visible>1</visible>
<invalid>1</invalid>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>images/uid.png</icon>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>autoFill:cn,%givenName% %sn%</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>4</order>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>images/lock.png</icon>
	<type>password</type>
	<verify>1</verify>
	<helper>
		<display>Encryption</display>
		<id>enc</id>
		<option>blowfish</option>
		<option>clear</option>
		<option>crypt</option>
		<option>ext_des</option>
		<option>md5</option>
		<option>md5crypt</option>
		<option>sha</option>
		<option>smd5</option>
		<option>ssha</option>
		<value>md5</value>
	</helper>
	<post>=php.Password(%enc%,%userPassword%)</post>
	<order>5</order>
	<spacer>1</spacer>
</attribute>

<attribute id="title">
	<display>Title</display>
	<icon>images/ou.png</icon>
	<order>6</order>
</attribute>
<attribute id="alias">
	<display>Alias</display>
	<order>7</order>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>8</order>
</attribute>
<attribute id="ou">
	<display>Organisational unit</display>
	<order>9</order>
</attribute>
<attribute id="roomNumber">
	<display>Room Number</display>
	<order>10</order>
	<spacer>1</spacer>
</attribute>

<attribute id="street">
	<display>Address</display>
	<icon>images/mail.png</icon>
	<order>11</order>
</attribute>
<attribute id="postOfficeBox">
	<display>Post box</display>
	<order>12</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>13</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>14</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>15</order>
</attribute>
<attribute id="c">
	<display>Country</display>
	<order>16</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>images/phone.png</icon>
	<order>17</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>18</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>19</order>
</attribute>
</attributes>
</template>

=== touv/node-sphinxapi-test/server/pkgi/phpldapadmin/etc/phpldapadmin/templates.pkgi-raw/creation/sendmailMTAMapObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">
<!--This template doesnt work needs modification to the Engine.-->
<template>
<title>Sendmail Relays</title>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<icon>images/mail.png</icon>
<description>New Sendmail Relays</description>
<askcontainer>1</askcontainer>
<rdn>sendmailMTACluster</rdn>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAClass"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>images/object.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Host/Network/Address</display>
	<option>RELAY: Allow host/network/address to relay</option>
	<option>OK: Accept local mail but disallow relay</option>
	<option>REJECT: Reject messages</option>
	<option>DISCARD: Discard messages</option>
	<option>SKIP: Apply default action to messages</option>
	<option>ERROR: Reject message with custom error</option>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAMapName">
	<value>access</value>
	<hidden>1</hidden>
</attribute>
</attributes>
</template>
